name = "Sangai"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "A clean, modern, and responsive Hugo theme inspired by the Sangai deer â€” built for blogs, portfolios, and storytelling."

homepage = "https://github.com/Koustubha-naik/Sangai"
demosite = "https://sangai.koustubha.com/"

tags = [
  "blog",
  "portfolio",
  "minimal",
  "clean",
  "modern",
  "responsive",
  "dark-mode",
  "lightweight",
  "personal",
  "documentation",
  "hugo-theme",
  "scss"
]

features = [
  "Dark / Light mode toggle",
  "Featured content slider",
  "Explore card section",
  "Responsive design",
  "Clean typography",
  "Fast build with Hugo Pipes",
  "SCSS-based styling",
  "Code highlighting",
  "Customizable layouts",
  "Optimized for Lighthouse performance",
  "Table of contents",
  "Social icons support"
]

min_version = "0.125.0"

[author]
  name = "Koustubha Naik"
  homepage = "https://github.com/Koustubha-naik/Sangai"
